site_name: Clovers' Blog
site_url: https://clovers2333.github.io
repo_url: https://github.com/Clovers2333/Clovers-Blog/
repo_name: Clovers2333/Clovers-Blog
edit_uri: tree/master/docs
copyright: Copyright &copy; 2025 Clovers

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  # custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)" # 主题颜色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: # 字体，大概率不需要换
    text: LXGW WenKai Screen GB Screen
    code: JetBrains Mono

markdown_extensions:
    - toc:
          permalink: true
          toc_depth: 4
    - meta
    - def_list
    - attr_list
    - md_in_html
    - sane_lists
    - admonition
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.magiclink
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.smartsymbols
    - neoteroi.spantable
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.highlight:
          anchor_linenums: true
          linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.arithmatex:
          generic: true

extra_css:
    - https://gcore.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
    - css/custom.css
    - css/card.css
    - css/tasklist.css
    - css/flink.css
    - css/more_changelog.css
    - css/neoteroi-mkdocs.css
    - css/fold_toc.css

extra_javascript:
    - css/Javascripts/katex.js
    - css/Javascripts/katex.min.js
    - css/Javascripts/toc.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
    # - css/Javascripts/mathjax.js
    # - css/Javascripts/tablesort.js
    # - css/Javascripts/polyfill.min.js
    # - https://unpkg.com/katex@0/dist/katex.min.js
    # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
    # - https://polyfill.io/v3/polyfill.min.js?features=es6
    # - https://gcore.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js

plugins:
  - search
  - statistics

not_in_nav: todo.md

nav:
  - Welcome:
    - 首页: index.md
    - 友链: links.md
  - Computer Science:
    - Index: cs/index.md
    - Introduction:
      - Bash Cheatsheet: cs/basic/bash_cheatsheet.md
      - MIT Missing Semester: cs/basic/MIT-Missing-Semester.md
      - 程序设计与算法基础: cs/basic/fpa.md
    - Languages:
      - Python:
        - CS61A: cs/languages/python/cs61a.md
        - cheatsheet: cs/languages/python/cheatsheet.md
      - C++:
        - oop:
          - Index: cs/languages/cpp/oop/index.md
          - 编程范式与 OOP 引入: cs/languages/cpp/oop/intro.md
          - 类：定义、成员、构造、析构: cs/languages/cpp/oop/class-1.md
          - 类：拷贝赋值、运算符重载与引用: cs/languages/cpp/oop/class-2.md
          - I/O Stream: cs/languages/cpp/oop/io.md
          - 模版: cs/languages/cpp/oop/template.md
          - 异常处理: cs/languages/cpp/oop/exception.md
          - 指针相关: cs/languages/cpp/oop/pointer.md
  #   - 前端三件套:
  #     - jaca script:
  #     - css:
  #     - html:
    - Data Structure:
      - 数据结构基础: cs/ds/fds.md
      - 高级数据结构与算法分析:
        - Index: cs/ds/ads/index.md
        - 数据结构全家桶: cs/ds/ads/ds.md
        - 回溯: cs/ds/ads/back.md
        - 分治: cs/ds/ads/divide.md
        - 贪心和动态规划: cs/ds/ads/greedy_DP.md
        - NP 问题: cs/ds/ads/NP.md
        - 近似算法: cs/ds/ads/Appr.md
        - 局部搜索: cs/ds/ads/LocalSearch.md
        - 随机化: cs/ds/ads/rand.md
        - 并行计算: cs/ds/ads/parallel.md
        - 外部排序: cs/ds/ads/external.md
    - 编译原理:
      - Index: cs/compiler/index.md
      - 计算理论基础: cs/compiler/tcs.md
      - 词法分析: cs/compiler/lexical.md
      - 语法分析: cs/compiler/syntax.md
      - 语义分析: cs/compiler/semantic.md
      - 运行时环境: cs/compiler/environment.md
      - 中间代码生成: cs/compiler/intermediate.md
      - 目标代码生成: cs/compiler/object.md
    - AI:
      - 人工智能引论:
        - Index: cs/ai/intro/index.md
        - 逻辑与推理: cs/ai/intro/logic.md
        - 搜索与求解: cs/ai/intro/search.md
        - 机器学习——监督学习: cs/ai/intro/ml_s.md
        - 机器学习——无监督学习: cs/ai/intro/ml_uns.md
        - 深度学习: cs/ai/intro/dl.md
        - 强化学习: cs/ai/intro/rl.md
        - 人工智能博弈: cs/ai/intro/game.md
      - CS229:
        - Index: cs/ai/cs229/index.md
        - Linear regression: cs/ai/cs229/chapter1.md
        - Logistic regression: cs/ai/cs229/chapter2.md
        - Generalized Linear Models: cs/ai/cs229/chapter3.md
        - Generative Learning Algorithms: cs/ai/cs229/chapter4.md
        - Kernel Methods: cs/ai/cs229/chapter5.md
        - Support Vector Machines: cs/ai/cs229/chapter6.md
    - System:
      - Languages:
        - CS61C: cs/system/languages/cs61c.md
        - Verilog Cheatsheet: cs/system/languages/v_cheatsheet.md
      - Operating System:
        - Index: cs/system/os/index.md
        - Introduction: cs/system/os/Intro.md
        - Structure: cs/system/os/Structure.md
        - Process: cs/system/os/Process.md
        - Scheduling: cs/system/os/Scheduling.md
        - Thread: cs/system/os/Thread.md
        - Synchronization: cs/system/os/Synchronization.md
        - Deadlock: cs/system/os/Deadlock.md
      - Books:
        - CSAPP:
          - Index: cs/system/books/csapp/index.md
          - Labs: cs/system/books/csapp/labs.md
          - Bits, Bytes and Integer: cs/system/books/csapp/Lec2-3.md
          - Floating Points: cs/system/books/csapp/Lec4.md
          - Machine-Level Programming: cs/system/books/csapp/Lec5-9.md
          - Optimizing: cs/system/books/csapp/Lec10.md
          - Processor Structure: cs/system/books/csapp/Lec11-13.md
        - 数字逻辑与计算机组成: cs/books/system/dlco.md
        - Digital Design and Computer Architecture: cs/books/system/ddca.md
  # - 信息安全:
  - Math:
    - Index: math/index.md
    - 线性代数:
      - Index: math/LinearAlgebra/index.md
      - 二次型: math/LinearAlgebra/quadratic.md
    - 线性规划基础:
      - Index: math/LinearProgramming/index.md
      - 线性规划几何基础: math/LinearProgramming/basic.md
      - 线性规划的对偶理论: math/LinearProgramming/dual.md
      - 拉格朗日对偶: math/LinearProgramming/lagrange.md
    - 近似算法:
      - Index: math/Appr/index.md
      - Introduction: math/Appr/ch1.md
      - Greedy Algorithms and Local Search: math/Appr/ch2.md
      - Rounding data and dynamic programming: math/Appr/ch3.md
      - Deterministic rounding of Linear Programs: math/Appr/ch4.md
      - Random sampling and randomized rounding of Linear Programs: math/Appr/ch5.md
      - Randomized rounding of semidefinite programs: math/Appr/ch6.md
      - The primal-dual method: math/Appr/ch7.md
      - Cuts and metrics: math/Appr/ch8.md
  - Economy & Finance:
    - 微观经济学: finance/micro.md
    - 公司金融:
      - Index: finance/corporate/index.md
      - 财务报表及模型: finance/corporate/intro.md
      - 现值计算及投资决策: finance/corporate/investment.md
      - 融资决策和资产定价: finance/corporate/financing.md
      - 股利政策: finance/corporate/dividend.md
  # - 杂项: 
  - Computing Economics:
    - 论文阅读:
      - Index: computing_eco/articles/index.md
      - 信息定价中的机制设计:
        - Index: computing_eco/articles/Information_Pricing_Mechanism/index.md
        - Moshe,Bobby: computing_eco/articles/Information_Pricing_Mechanism/Moshe,Bobby.md
        - Yiling,Haifeng,Shuran: computing_eco/articles/Information_Pricing_Mechanism/Yiling,Haifeng,Shuran.md
    - 24-25春夏讨论班:
      - Index: computing_eco/24-25class/index.md
      - 博弈论与计算经济: 
        - Index: computing_eco/24-25class/ec/index.md
        - 博弈论基础回顾: computing_eco/24-25class/ec/game_review.md
        - 零和博弈与 Min-Max 定理: computing_eco/24-25class/ec/minmax.md
        - 贝叶斯劝说: computing_eco/24-25class/ec/bayesian.md
        - 社会选择理论基础: computing_eco/24-25class/ec/social_choice.md
      - 拍卖理论:
        - Index: computing_eco/24-25class/auction/index.md
        - 私有价值拍卖，收入等价原理: computing_eco/24-25class/auction/basic.md
        - 拍卖中的机制设计: computing_eco/24-25class/auction/mechanism.md
        - 关联价值拍卖，收入排序原理: computing_eco/24-25class/auction/ranking.md
      - 均衡的计算: 
        - Index: computing_eco/24-25class/equilibrium/index.md
      - 机制设计:
        - Index: computing_eco/24-25class/mechanism/index.md
        - Truthful Fair Division: computing_eco/24-25class/mechanism/fair_division.md
        - Aggregation of Antagonistic Contingent Preferences: computing_eco/24-25class/mechanism/aggregation.md
        - 不含钱机制设计: computing_eco/24-25class/mechanism/no_money_mechanism.md
  - Misc:
    - Index: misc/index.md
    - Summaries:
      - 23-24寒假总结: misc/summary/23-24_winter_summary.md
      - 24-25秋冬学期总结: misc/summary/24-25_first_summary.md
      - 24-25春夏学期总结: misc/summary/24-25_second_summary.md

